// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEST_PFE.Models;

#nullable disable

namespace TEST_PFE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250222113008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEST_PFE.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OpenRevenue")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("openRevenue");

                    b.Property<decimal?>("OpenRevenueBase")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("openRevenueBase");

                    b.Property<int?>("Opendeals")
                        .HasColumnType("int")
                        .HasColumnName("opendeals");

                    b.Property<Guid?>("OriginatingLead")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("originatingLead");

                    b.Property<Guid?>("PreferredEquipement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("preferredEquipement");

                    b.Property<string>("PreferredService")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferredService");

                    b.Property<string>("Territory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("territory");

                    b.HasKey("AccountId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("TEST_PFE.Models.ConfigurationTable", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConfigID");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductID");

                    b.HasKey("ConfigId")
                        .HasName("PK__Configur__C3BC333CC4499F4F");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProductId");

                    b.ToTable("ConfigurationTable", (string)null);
                });

            modelBuilder.Entity("TEST_PFE.Models.DestinationOleDb", b =>
                {
                    b.Property<int?>("Accountcategorycode")
                        .HasColumnType("int")
                        .HasColumnName("accountcategorycode");

                    b.Property<string>("Accountcategorycodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountcategorycodename");

                    b.Property<int?>("Accountclassificationcode")
                        .HasColumnType("int")
                        .HasColumnName("accountclassificationcode");

                    b.Property<string>("Accountclassificationcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountclassificationcodename");

                    b.Property<Guid?>("Accountid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("accountid");

                    b.Property<string>("Accountnumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("accountnumber");

                    b.Property<int?>("Accountratingcode")
                        .HasColumnType("int")
                        .HasColumnName("accountratingcode");

                    b.Property<string>("Accountratingcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountratingcodename");

                    b.Property<Guid?>("Address1Addressid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address1_addressid");

                    b.Property<int?>("Address1Addresstypecode")
                        .HasColumnType("int")
                        .HasColumnName("address1_addresstypecode");

                    b.Property<string>("Address1Addresstypecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address1_addresstypecodename");

                    b.Property<string>("Address1City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("address1_city");

                    b.Property<string>("Address1Composite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address1_composite");

                    b.Property<string>("Address1Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("address1_country");

                    b.Property<string>("Address1County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_county");

                    b.Property<string>("Address1Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_fax");

                    b.Property<int?>("Address1Freighttermscode")
                        .HasColumnType("int")
                        .HasColumnName("address1_freighttermscode");

                    b.Property<string>("Address1Freighttermscodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address1_freighttermscodename");

                    b.Property<double?>("Address1Latitude")
                        .HasColumnType("float")
                        .HasColumnName("address1_latitude");

                    b.Property<string>("Address1Line1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address1_line1");

                    b.Property<string>("Address1Line2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address1_line2");

                    b.Property<string>("Address1Line3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address1_line3");

                    b.Property<double?>("Address1Longitude")
                        .HasColumnType("float")
                        .HasColumnName("address1_longitude");

                    b.Property<string>("Address1Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address1_name");

                    b.Property<string>("Address1Postalcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("address1_postalcode");

                    b.Property<string>("Address1Postofficebox")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("address1_postofficebox");

                    b.Property<string>("Address1Primarycontactname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address1_primarycontactname");

                    b.Property<int?>("Address1Shippingmethodcode")
                        .HasColumnType("int")
                        .HasColumnName("address1_shippingmethodcode");

                    b.Property<string>("Address1Shippingmethodcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address1_shippingmethodcodename");

                    b.Property<string>("Address1Stateorprovince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_stateorprovince");

                    b.Property<string>("Address1Telephone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_telephone1");

                    b.Property<string>("Address1Telephone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_telephone2");

                    b.Property<string>("Address1Telephone3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address1_telephone3");

                    b.Property<string>("Address1Upszone")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("address1_upszone");

                    b.Property<int?>("Address1Utcoffset")
                        .HasColumnType("int")
                        .HasColumnName("address1_utcoffset");

                    b.Property<Guid?>("Address2Addressid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address2_addressid");

                    b.Property<int?>("Address2Addresstypecode")
                        .HasColumnType("int")
                        .HasColumnName("address2_addresstypecode");

                    b.Property<string>("Address2Addresstypecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address2_addresstypecodename");

                    b.Property<string>("Address2City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("address2_city");

                    b.Property<string>("Address2Composite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address2_composite");

                    b.Property<string>("Address2Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("address2_country");

                    b.Property<string>("Address2County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_county");

                    b.Property<string>("Address2Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_fax");

                    b.Property<int?>("Address2Freighttermscode")
                        .HasColumnType("int")
                        .HasColumnName("address2_freighttermscode");

                    b.Property<string>("Address2Freighttermscodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address2_freighttermscodename");

                    b.Property<double?>("Address2Latitude")
                        .HasColumnType("float")
                        .HasColumnName("address2_latitude");

                    b.Property<string>("Address2Line1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address2_line1");

                    b.Property<string>("Address2Line2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address2_line2");

                    b.Property<string>("Address2Line3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address2_line3");

                    b.Property<double?>("Address2Longitude")
                        .HasColumnType("float")
                        .HasColumnName("address2_longitude");

                    b.Property<string>("Address2Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address2_name");

                    b.Property<string>("Address2Postalcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("address2_postalcode");

                    b.Property<string>("Address2Postofficebox")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("address2_postofficebox");

                    b.Property<string>("Address2Primarycontactname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address2_primarycontactname");

                    b.Property<int?>("Address2Shippingmethodcode")
                        .HasColumnType("int")
                        .HasColumnName("address2_shippingmethodcode");

                    b.Property<string>("Address2Shippingmethodcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address2_shippingmethodcodename");

                    b.Property<string>("Address2Stateorprovince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_stateorprovince");

                    b.Property<string>("Address2Telephone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_telephone1");

                    b.Property<string>("Address2Telephone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_telephone2");

                    b.Property<string>("Address2Telephone3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address2_telephone3");

                    b.Property<string>("Address2Upszone")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("address2_upszone");

                    b.Property<int?>("Address2Utcoffset")
                        .HasColumnType("int")
                        .HasColumnName("address2_utcoffset");

                    b.Property<string>("AdxCreatedbyipaddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adx_createdbyipaddress");

                    b.Property<string>("AdxCreatedbyusername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adx_createdbyusername");

                    b.Property<string>("AdxModifiedbyipaddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adx_modifiedbyipaddress");

                    b.Property<string>("AdxModifiedbyusername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adx_modifiedbyusername");

                    b.Property<decimal?>("Aging30")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("aging30");

                    b.Property<decimal?>("Aging30Base")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("aging30_base");

                    b.Property<decimal?>("Aging60")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("aging60");

                    b.Property<decimal?>("Aging60Base")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("aging60_base");

                    b.Property<decimal?>("Aging90")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("aging90");

                    b.Property<decimal?>("Aging90Base")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("aging90_base");

                    b.Property<int?>("Businesstypecode")
                        .HasColumnType("int")
                        .HasColumnName("businesstypecode");

                    b.Property<string>("Businesstypecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("businesstypecodename");

                    b.Property<Guid?>("Createdby")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createdby");

                    b.Property<Guid?>("Createdbyexternalparty")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createdbyexternalparty");

                    b.Property<string>("Createdbyexternalpartyname")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("createdbyexternalpartyname");

                    b.Property<string>("Createdbyexternalpartyyominame")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("createdbyexternalpartyyominame");

                    b.Property<string>("Createdbyname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("createdbyname");

                    b.Property<string>("Createdbyyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("createdbyyominame");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("datetime")
                        .HasColumnName("createdon");

                    b.Property<Guid?>("Createdonbehalfby")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createdonbehalfby");

                    b.Property<string>("Createdonbehalfbyname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("createdonbehalfbyname");

                    b.Property<string>("Createdonbehalfbyyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("createdonbehalfbyyominame");

                    b.Property<decimal?>("Creditlimit")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("creditlimit");

                    b.Property<decimal?>("CreditlimitBase")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("creditlimit_base");

                    b.Property<bool?>("Creditonhold")
                        .HasColumnType("bit")
                        .HasColumnName("creditonhold");

                    b.Property<string>("Creditonholdname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("creditonholdname");

                    b.Property<int?>("Customersizecode")
                        .HasColumnType("int")
                        .HasColumnName("customersizecode");

                    b.Property<string>("Customersizecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customersizecodename");

                    b.Property<int?>("Customertypecode")
                        .HasColumnType("int")
                        .HasColumnName("customertypecode");

                    b.Property<string>("Customertypecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customertypecodename");

                    b.Property<Guid?>("Defaultpricelevelid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("defaultpricelevelid");

                    b.Property<string>("Defaultpricelevelidname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("defaultpricelevelidname");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("Donotbulkemail")
                        .HasColumnType("bit")
                        .HasColumnName("donotbulkemail");

                    b.Property<string>("Donotbulkemailname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotbulkemailname");

                    b.Property<bool?>("Donotbulkpostalmail")
                        .HasColumnType("bit")
                        .HasColumnName("donotbulkpostalmail");

                    b.Property<string>("Donotbulkpostalmailname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotbulkpostalmailname");

                    b.Property<bool?>("Donotemail")
                        .HasColumnType("bit")
                        .HasColumnName("donotemail");

                    b.Property<string>("Donotemailname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotemailname");

                    b.Property<bool?>("Donotfax")
                        .HasColumnType("bit")
                        .HasColumnName("donotfax");

                    b.Property<string>("Donotfaxname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotfaxname");

                    b.Property<bool?>("Donotphone")
                        .HasColumnType("bit")
                        .HasColumnName("donotphone");

                    b.Property<string>("Donotphonename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotphonename");

                    b.Property<bool?>("Donotpostalmail")
                        .HasColumnType("bit")
                        .HasColumnName("donotpostalmail");

                    b.Property<string>("Donotpostalmailname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotpostalmailname");

                    b.Property<string>("Donotsendmarketingmaterialname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("donotsendmarketingmaterialname");

                    b.Property<bool?>("Donotsendmm")
                        .HasColumnType("bit")
                        .HasColumnName("donotsendmm");

                    b.Property<string>("Emailaddress1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emailaddress1");

                    b.Property<string>("Emailaddress2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emailaddress2");

                    b.Property<string>("Emailaddress3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emailaddress3");

                    b.Property<byte[]>("Entityimage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("entityimage");

                    b.Property<long?>("EntityimageTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("entityimage_timestamp");

                    b.Property<string>("EntityimageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("entityimage_url");

                    b.Property<Guid?>("Entityimageid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entityimageid");

                    b.Property<decimal?>("Exchangerate")
                        .HasColumnType("decimal(28, 12)")
                        .HasColumnName("exchangerate");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fax");

                    b.Property<bool?>("Followemail")
                        .HasColumnType("bit")
                        .HasColumnName("followemail");

                    b.Property<string>("Followemailname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("followemailname");

                    b.Property<string>("Ftpsiteurl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ftpsiteurl");

                    b.Property<int?>("Importsequencenumber")
                        .HasColumnType("int")
                        .HasColumnName("importsequencenumber");

                    b.Property<int?>("Industrycode")
                        .HasColumnType("int")
                        .HasColumnName("industrycode");

                    b.Property<string>("Industrycodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("industrycodename");

                    b.Property<string>("Isprivatename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("isprivatename");

                    b.Property<DateTime?>("Lastonholdtime")
                        .HasColumnType("datetime")
                        .HasColumnName("lastonholdtime");

                    b.Property<DateTime?>("Lastusedincampaign")
                        .HasColumnType("datetime")
                        .HasColumnName("lastusedincampaign");

                    b.Property<decimal?>("Marketcap")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("marketcap");

                    b.Property<decimal?>("MarketcapBase")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("marketcap_base");

                    b.Property<bool?>("Marketingonly")
                        .HasColumnType("bit")
                        .HasColumnName("marketingonly");

                    b.Property<string>("Marketingonlyname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("marketingonlyname");

                    b.Property<string>("Masteraccountidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("masteraccountidname");

                    b.Property<string>("Masteraccountidyominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("masteraccountidyominame");

                    b.Property<Guid?>("Masterid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("masterid");

                    b.Property<bool?>("Merged")
                        .HasColumnType("bit")
                        .HasColumnName("merged");

                    b.Property<string>("Mergedname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mergedname");

                    b.Property<Guid?>("Modifiedby")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("modifiedby");

                    b.Property<Guid?>("Modifiedbyexternalparty")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("modifiedbyexternalparty");

                    b.Property<string>("Modifiedbyexternalpartyname")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("modifiedbyexternalpartyname");

                    b.Property<string>("Modifiedbyexternalpartyyominame")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("modifiedbyexternalpartyyominame");

                    b.Property<string>("Modifiedbyname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("modifiedbyname");

                    b.Property<string>("Modifiedbyyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("modifiedbyyominame");

                    b.Property<DateTime?>("Modifiedon")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedon");

                    b.Property<Guid?>("Modifiedonbehalfby")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("modifiedonbehalfby");

                    b.Property<string>("Modifiedonbehalfbyname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("modifiedonbehalfbyname");

                    b.Property<string>("Modifiedonbehalfbyyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("modifiedonbehalfbyyominame");

                    b.Property<Guid?>("MsaManagingpartnerid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("msa_managingpartnerid");

                    b.Property<string>("MsaManagingpartneridname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("msa_managingpartneridname");

                    b.Property<string>("MsaManagingpartneridyominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("msa_managingpartneridyominame");

                    b.Property<Guid?>("MsdynAccountkpiid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("msdyn_accountkpiid");

                    b.Property<string>("MsdynAccountkpiidname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("msdyn_accountkpiidname");

                    b.Property<bool?>("MsdynGdproptout")
                        .HasColumnType("bit")
                        .HasColumnName("msdyn_gdproptout");

                    b.Property<string>("MsdynGdproptoutname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("msdyn_gdproptoutname");

                    b.Property<int?>("MsdynPrimarytimezone")
                        .HasColumnType("int")
                        .HasColumnName("msdyn_primarytimezone");

                    b.Property<Guid?>("MsdynSalesaccelerationinsightid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("msdyn_salesaccelerationinsightid");

                    b.Property<string>("MsdynSalesaccelerationinsightidname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("msdyn_salesaccelerationinsightidname");

                    b.Property<string>("Name")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<int?>("Numberofemployees")
                        .HasColumnType("int")
                        .HasColumnName("numberofemployees");

                    b.Property<int?>("Onholdtime")
                        .HasColumnType("int")
                        .HasColumnName("onholdtime");

                    b.Property<int?>("Opendeals")
                        .HasColumnType("int")
                        .HasColumnName("opendeals");

                    b.Property<DateTime?>("OpendealsDate")
                        .HasColumnType("datetime")
                        .HasColumnName("opendeals_date");

                    b.Property<int?>("OpendealsState")
                        .HasColumnType("int")
                        .HasColumnName("opendeals_state");

                    b.Property<decimal?>("Openrevenue")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("openrevenue");

                    b.Property<decimal?>("OpenrevenueBase")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("openrevenue_base");

                    b.Property<DateTime?>("OpenrevenueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("openrevenue_date");

                    b.Property<int?>("OpenrevenueState")
                        .HasColumnType("int")
                        .HasColumnName("openrevenue_state");

                    b.Property<Guid?>("Originatingleadid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("originatingleadid");

                    b.Property<string>("Originatingleadidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("originatingleadidname");

                    b.Property<string>("Originatingleadidyominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("originatingleadidyominame");

                    b.Property<DateTime?>("Overriddencreatedon")
                        .HasColumnType("datetime")
                        .HasColumnName("overriddencreatedon");

                    b.Property<Guid?>("Ownerid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ownerid");

                    b.Property<string>("Owneridname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("owneridname");

                    b.Property<string>("Owneridtype")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owneridtype");

                    b.Property<string>("Owneridyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("owneridyominame");

                    b.Property<int?>("Ownershipcode")
                        .HasColumnType("int")
                        .HasColumnName("ownershipcode");

                    b.Property<string>("Ownershipcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ownershipcodename");

                    b.Property<Guid?>("Owningbusinessunit")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owningbusinessunit");

                    b.Property<string>("Owningbusinessunitname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("owningbusinessunitname");

                    b.Property<Guid?>("Owningteam")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owningteam");

                    b.Property<Guid?>("Owninguser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owninguser");

                    b.Property<Guid?>("Parentaccountid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parentaccountid");

                    b.Property<string>("Parentaccountidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("parentaccountidname");

                    b.Property<string>("Parentaccountidyominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("parentaccountidyominame");

                    b.Property<bool?>("Participatesinworkflow")
                        .HasColumnType("bit")
                        .HasColumnName("participatesinworkflow");

                    b.Property<string>("Participatesinworkflowname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("participatesinworkflowname");

                    b.Property<int?>("Paymenttermscode")
                        .HasColumnType("int")
                        .HasColumnName("paymenttermscode");

                    b.Property<string>("Paymenttermscodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymenttermscodename");

                    b.Property<int?>("Preferredappointmentdaycode")
                        .HasColumnType("int")
                        .HasColumnName("preferredappointmentdaycode");

                    b.Property<string>("Preferredappointmentdaycodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preferredappointmentdaycodename");

                    b.Property<int?>("Preferredappointmenttimecode")
                        .HasColumnType("int")
                        .HasColumnName("preferredappointmenttimecode");

                    b.Property<string>("Preferredappointmenttimecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preferredappointmenttimecodename");

                    b.Property<int?>("Preferredcontactmethodcode")
                        .HasColumnType("int")
                        .HasColumnName("preferredcontactmethodcode");

                    b.Property<string>("Preferredcontactmethodcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preferredcontactmethodcodename");

                    b.Property<Guid?>("Preferredequipmentid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("preferredequipmentid");

                    b.Property<string>("Preferredequipmentidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("preferredequipmentidname");

                    b.Property<Guid?>("Preferredserviceid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("preferredserviceid");

                    b.Property<string>("Preferredserviceidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("preferredserviceidname");

                    b.Property<Guid?>("Preferredsystemuserid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("preferredsystemuserid");

                    b.Property<string>("Preferredsystemuseridname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("preferredsystemuseridname");

                    b.Property<string>("Preferredsystemuseridyominame")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("preferredsystemuseridyominame");

                    b.Property<Guid?>("Primarycontactid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("primarycontactid");

                    b.Property<string>("Primarycontactidname")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("primarycontactidname");

                    b.Property<string>("Primarycontactidyominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("primarycontactidyominame");

                    b.Property<string>("Primarysatoriid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("primarysatoriid");

                    b.Property<string>("Primarytwitterid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("primarytwitterid");

                    b.Property<Guid?>("Processid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processid");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(28, 2)")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("RevenueBase")
                        .HasColumnType("decimal(28, 4)")
                        .HasColumnName("revenue_base");

                    b.Property<int?>("Sharesoutstanding")
                        .HasColumnType("int")
                        .HasColumnName("sharesoutstanding");

                    b.Property<int?>("Shippingmethodcode")
                        .HasColumnType("int")
                        .HasColumnName("shippingmethodcode");

                    b.Property<string>("Shippingmethodcodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shippingmethodcodename");

                    b.Property<string>("Sic")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sic");

                    b.Property<Guid?>("Slaid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slaid");

                    b.Property<Guid?>("Slainvokedid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slainvokedid");

                    b.Property<string>("Slainvokedidname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slainvokedidname");

                    b.Property<string>("Slaname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slaname");

                    b.Property<Guid?>("Stageid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("stageid");

                    b.Property<int?>("Statecode")
                        .HasColumnType("int")
                        .HasColumnName("statecode");

                    b.Property<string>("Statecodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("statecodename");

                    b.Property<int?>("Statuscode")
                        .HasColumnType("int")
                        .HasColumnName("statuscode");

                    b.Property<string>("Statuscodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("statuscodename");

                    b.Property<string>("Stockexchange")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("stockexchange");

                    b.Property<int?>("Teamsfollowed")
                        .HasColumnType("int")
                        .HasColumnName("teamsfollowed");

                    b.Property<string>("Telephone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telephone1");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telephone2");

                    b.Property<string>("Telephone3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telephone3");

                    b.Property<int?>("Territorycode")
                        .HasColumnType("int")
                        .HasColumnName("territorycode");

                    b.Property<string>("Territorycodename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("territorycodename");

                    b.Property<Guid?>("Territoryid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("territoryid");

                    b.Property<string>("Territoryidname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("territoryidname");

                    b.Property<string>("Tickersymbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tickersymbol");

                    b.Property<string>("Timespentbymeonemailandmeetings")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)")
                        .HasColumnName("timespentbymeonemailandmeetings");

                    b.Property<int?>("Timezoneruleversionnumber")
                        .HasColumnType("int")
                        .HasColumnName("timezoneruleversionnumber");

                    b.Property<Guid?>("Transactioncurrencyid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transactioncurrencyid");

                    b.Property<string>("Transactioncurrencyidname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transactioncurrencyidname");

                    b.Property<string>("Traversedpath")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)")
                        .HasColumnName("traversedpath");

                    b.Property<int?>("Utcconversiontimezonecode")
                        .HasColumnType("int")
                        .HasColumnName("utcconversiontimezonecode");

                    b.Property<long?>("Versionnumber")
                        .HasColumnType("bigint")
                        .HasColumnName("versionnumber");

                    b.Property<string>("Websiteurl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("websiteurl");

                    b.Property<string>("Yominame")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("yominame");

                    b.ToTable("Destination OLE DB", (string)null);
                });

            modelBuilder.Entity("TEST_PFE.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("productId");

                    b.Property<decimal?>("CurrentCost")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("currentCost");

                    b.Property<string>("DefaultUoMidName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("defaultUoMidName");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<string>("ProductNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productNumber");

                    b.Property<string>("ProductStructureName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productStructureName");

                    b.Property<int?>("ProductTypeCode")
                        .HasColumnType("int")
                        .HasColumnName("productTypeCode");

                    b.Property<decimal?>("QuantityOnHand")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("StantardCost")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("stantardCost");

                    b.Property<string>("StateCodeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("stateCodeName");

                    b.Property<string>("StatusCodeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statusCodeName");

                    b.Property<decimal?>("StockVolume")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("stockVolume");

                    b.Property<decimal?>("StockWeight")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("stockWeight");

                    b.Property<DateTime?>("ValidFromDate")
                        .HasColumnType("date");

                    b.HasKey("ProductId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("TEST_PFE.Models.ConfigurationTable", b =>
                {
                    b.HasOne("TEST_PFE.Models.Account", "Account")
                        .WithMany("ConfigurationTables")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Configuration_Account");

                    b.HasOne("TEST_PFE.Models.Product", "Product")
                        .WithMany("ConfigurationTables")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Configuration_Product");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TEST_PFE.Models.Account", b =>
                {
                    b.Navigation("ConfigurationTables");
                });

            modelBuilder.Entity("TEST_PFE.Models.Product", b =>
                {
                    b.Navigation("ConfigurationTables");
                });
#pragma warning restore 612, 618
        }
    }
}
